spring:
  application:
    name: ai-sandbox
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/ai_sandbox
    username: ai_user
    password: 12345678
  ai:
    ollama:
      base-url: http://localhost:11431
      chat:
        model: llama3.2:3b

server:
  port: 18080